### ISSUE TITLE
Public and Private

### ISSUE THREAD

**Issue by aarushbhutra** [imperialvalordev/helpdesk#1]
### Feature

I request that "https://github.com/imperialvalordev/request" and "https://github.com/imperialvalordev/TitanAPI" are private, I am not a 100% sure but we don't want anyone to be able to use titan api unless we work on a api which is meant for used

### Ideal solution or implementation

Make them private

### Other context

N/A

### The platform for which your plugin is to be built against

N/A

**Comment by chriscn** [comment]
1. `request` must be public because of issue templates
2. `TitanAPI` is meant to be an open API + it needs to be to allow the custom deploy solution.
