### ISSUE TITLE
discord.imperialvalor.net

### ISSUE THREAD

**Issue by aarushbhutra** [imperialvalordev/helpdesk#10]
### Feature

Via cloudfare please add a redirect for discord.imperialvalor.net to our discord

### Ideal solution or implementation

Add a redirect via cloudfare

### Alternative solutions or implementations

Not sure

### Other context

N/A

### The platform for which your plugin is to be built against

N/A

**Comment by Whitescan** [comment]
@aarushbhutra you should assign someone that is capable of doing so...

**Comment by aarushbhutra** [comment]
@chriscn Please do this, shouldn't be too hard

**Comment by Whitescan** [comment]
@aarushbhutra since Thorin was kicked you might want to look into this.

**Comment by aarushbhutra** [comment]
Can't find a way
