### ISSUE TITLE
Fallback

### ISSUE THREAD

**Issue by aarushbhutra** [imperialvalordev/helpdesk#11]
### Feature

I want a plugin which when a gameserver crashes is sent to the hub which are in config.yml

config.yml example:
hub:
- "lobby1"
- "lobby2"

hub-crash: "&cImperial&7Valor : It looks like the hub servers are offline! join discord.imperialvalor.net for more info!"

### Ideal solution or implementation

N/A

### Alternative solutions or implementations

N/A

### Other context

N/A

### The platform for which your plugin is to be built against

Bungee

**Comment by chriscn** [comment]
This helpdesk if not for matters that can be simply be [Google'd](https://lmgtfy.app/?q=bungeecord+fallback+server).

**Comment by aarushbhutra** [comment]
Not needed currently
