### ISSUE TITLE
Mirror Skin

### ISSUE THREAD

**Issue by aarushbhutra** [imperialvalordev/helpdesk#13]
### Feature

I am looking for a way for citizens npc to mirror the players skin, so it will be different for each player

Below is an example 
![image](https://user-images.githubusercontent.com/67967009/162578358-eb215580-4291-4f8a-996f-2fa94d413fc4.png)

### Ideal solution or implementation

Maybe a command like /reflectskin when whichever npc is selected will reflect the skin

### Alternative solutions or implementations

N/A

### Other context

N/A

### The platform for which your plugin is to be built against

Spigot/Paper

**Comment by Whitescan** [comment]
Answered in https://discord.com/channels/@me/950762076362657822/962361703612436491

Keeping this open if more questions occure around that topic for now?
