### ISSUE TITLE
Add 6v6v6v6 to Bedwars

### ISSUE THREAD

**Issue by West107** [imperialvalordev/helpdesk#17]
### Feature

This is a mode with 4 teams of 6 on a larger map. Everything will be the same as 4v4v4v4 except for the size of the map and players per team. Custom maps will also be made which include. 

Titans- Godzilla fighting mothra with battleships as islands, diamond gens are military bases 

Final Frontier- Each team is a Federation StarShip and the center is a Deep Space 9, the diamond gens are Klingon Birds of Prey 

Replace 4v4 with 6v6v6v6

### Ideal solution or implementation

Testing will begin on May 20th, release will be on 27th.

### The platform for which your plugin is to be built against

Minecraft

**Comment by West107** [comment]
> Do you want 4v4v4v4 entirely removed or a new gamemode for it added?

We curently have 4v4v4v4 and 4v4. **### 4v4** needs to be replaced by 6v6v6v6

**Comment by aarushbhutra** [comment]
Ah ok

**Comment by aarushbhutra** [comment]
Revamp in the works
