### ISSUE TITLE
Spawn area bedwars

### ISSUE THREAD

**Issue by West107** [imperialvalordev/helpdesk#18]
### Issue description

When in a bedwars game, you can see the area where you spawn at the start of the game. 

### Please specify which server you were on.

Bedwars 

### Priority this issue should have

Medium (should be fixed soon)

**Comment by aarushbhutra** [comment]
Screenshot? @West107

**Comment by aarushbhutra** [comment]
Can you use an alt to do it? @West107

**Comment by aarushbhutra** [comment]
Revamp in the works
