### ISSUE TITLE
People cannot join Bedwars

### ISSUE THREAD

**Issue by West107** [imperialvalordev/helpdesk#21]
### Issue description

People can only join the bedwars modes 4v4 and 1v1. It says "Unknown argument" on others

### Please specify which server you were on.

People can only join the bedwars modes 4v4 and 1v1. It says "Unknown argument" on others

### Operating system

Bedwars

### Priority this issue should have

Medium (should be fixed soon)

**Comment by aarushbhutra** [comment]
@West107 Screenshot
