### ISSUE TITLE
Kit PVP

### ISSUE THREAD

**Issue by West107** [imperialvalordev/helpdesk#22]
### Feature

Have people only be able to have 1 kit at a time. 1 Premium or 1 regular 

### Ideal solution or implementation

Anyway possible

### The platform for which your plugin is to be built against

Any

**Comment by aarushbhutra** [comment]
@Whitescan Could you make a plugin to make people not be able to enter an area? I can just add a plugin to tp the player out of the spawn area I just need you to find a way to not let them in again
