### ISSUE TITLE
Make premium kits accessible to all players

### ISSUE THREAD

**Issue by West107** [imperialvalordev/helpdesk#23]
### Feature

Premium kits in Kitpvp can be obtained through 500 kills in the gamemode

### Ideal solution or implementation

Barrier of entry could also be 5 hours playtime or something else instead of 500 kills but 500 kills best one to do. 

### The platform for which your plugin is to be built against

Any

**Comment by aarushbhutra** [comment]
Needs custom plugin @Whitescan

**Comment by aarushbhutra** [comment]
Revamp in the works
