### ISSUE TITLE
KitPVP issues/changes

### ISSUE THREAD

**Issue by West107** [imperialvalordev/helpdesk#27]
### Feature

1. Items in PVP need to not break
2. No land should be able to be broken 
3. should not be able to do /back after death
4. People do not get money from killing (should be 50$ per kill)
5. Move the Leaderboards 
6. leaderboards don't make sense - Blaze has a 5 streak but no kills
7. Get rid of the /shop line in the welcome holograms 
8. There are barrier blocks in front of stairs
9. Get rid of the discord hologram line 

### Ideal solution or implementation

Any

### The platform for which your plugin is to be built against

Any

**Comment by aarushbhutra** [comment]
1. WIP
2. Done
3. Done
4. https://github.com/imperialvalordev/helpdesk/issues/25
5. Done
6. Done
7. Done
8. Done
9. Done
