### ISSUE TITLE
Lobby Changes

### ISSUE THREAD

**Issue by West107** [imperialvalordev/helpdesk#28]
### Feature

1. Make the world only void 
2. Everyone on Staff is Sr.Dev except for me
3. Imperial Valor socials - sends link to discord, tiktok
4. Get rid of website in server info and tab
5. Get rid of discord on tab 
6. Get rid of Gamemodes on side tab
7. Get rid of hide and seek gamemode 
8. Kitpvp should say - Expansive map with custom kits to pvp your friends with
9. Bedwars should say - Protect your bed solo or in teams while trying to eliminate other players and beds
10. Make npc's centered 
11. Get rid of floating blocks over npc heads
12. Only have 1 lobby (no more in the nether star)
13. Get rid of gamemodes we don't have in server selector 
14. Get rid of twitter and instagram in server selector 
15. Bedwars and Kitpvp descriptions should be the same as 8 and 9
16. Discord in server selector should say - Join our discord server to interact with the community, receive updates, and win rewards! (make the link work too)
17. Store in server selector should say - Checkout the server store to enhance your playing experience (make it work as well)
18. Get rid of server new npc 
19. Have the welcome hologram say - Welcome to Imperial Valor. click the compass to get playing

### Ideal solution or implementation

Best way

### The platform for which your plugin is to be built against

Best one

**Comment by aarushbhutra** [comment]
1. I would make it all void however there are all the npc's and holograms for othergames which I dont to destroy everything else is gone
2. Done
3. WIP
4. Done
5. Done
6. Do you want me to get rid of all or just the ones not released?

Others are in work

**Comment by aarushbhutra** [comment]
7. Done
8. Done
9. Done
10. Done
11. Done
12. Done
13. Done
14. Done
15. Done
16. Done
17. Done
18. Done
19. Done

**Comment by West107** [comment]
1. Make every land out of render distances is best then
6. All gamemodes
