### ISSUE TITLE
Survival Economy

### ISSUE THREAD

**Issue by West107** [imperialvalordev/helpdesk#31]
# Item                   Quantity      Buy Price        Sell Price

Cobblestone          1            50 Cents          25 Cents
Stone                     1            50 Cents          25 Cents
Granite                  1            50 Cents          25 Cents
Diorite                   1            50 Cents          25 Cents
Andesite                1            50 Cents          25 Cents
Grass Block            1            65 Cents          35 Cents
Dirt Block               1            50 Cents          25 Cents
Oak Planks             1            50 Cents          25 Cents
Spruce Planks        1            50 Cents          25 Cents
Birch Planks           1            50 Cents          25 Cents
Jungle Planks         1            50 Cents          25 Cents
Acacia Planks         1            50 Cents          25 Cents
Dark Oak Planks    1            50 Cents          25 Cents
Crimson Planks     1             50 Cents          25 Cents
Warped Planks      1             50 Cents          25 Cents
All logs                  1             2 Dollars         1 Dollar 
Sand                      1             50 Cents          25 Cents
Sandstone             1             2 Dollars          50 Cents
All Glass                1             2 Dollars           1 Dollar 
All Wool                1             2 Dollars           1.50 Dollar
Gold Ingot            1             35 Dollars          20 Dollars 
Gold Block            1             315 Dollars        180 Dollars
Iron ingot             1               10 Dollars           5 Dollars
Iron Block             1             90 Dollars           45 Dollars
Quartz                  1               10 Dollars           5 Dollars
Quartz Block        1             90 Dollars           45 Dollars
Brick Block           1              5 Dollars             3 Dollars
Obsidian              1              3 Dollars             1.50 Dollar
Pumpkin              1               2 Dollars             1.50 cents
Netherrack          1               50 Cents              25 cents
Soul Sand           1               1.50 Dollar           1 Dollar      
Soul Soil             1               1.50 Dollar           1 Dollar
Ice                      1                1.50 Dollars         1 Dollar
Basalt                 1                3 Dollars              2 dollars
End Stone          1                2 Dollars              1 dollar
Emerald Ore      1                100 Dollars           50 dollars
Emerald             1                20 Dollars             5 Dollars
Emerald Block   1                180 Dollars           45 Dollars
All Terracotta    1                  3 Dollars               2 dollars
Melon Block     1                 2 Dollars              1.50 cents
Hay Bale           1                 7 Dollars              5 Dollars
Coal                  1                 4 Dollars              2 dollars
Coal Block        1                 36 Dollars            18 dollars
Prismarine S     1                 50 Cents              25 Cents
Prismarine C     1                 50 Cents              25 Cents
Concrete          1                  2.50 Dollars         1 Dollar
Concrete P       1                  2.50 Dollars         1 Dollar
Dried Kelp B    1                  8 Dollars               4 Dollars
Netherite S      1                  400 Dollars          100 Dollars
Netherite I       1                 1,740 Dollars         1000 Dollars
Netherite B      1                 15,660 Dollars       15000 Dollars
Blackstone       1                  4.50 Dollars         2 Dollars
Glowstone B    1                  5 Dollars              3 dollars
Magma Block  1                   5 Dollars              3.50 dollars
Sugar Cane     1                   1 Dollar                50 cents
Bamboo          1                   50 Cents              25 cents
Cactus             1                   1.50 Cents           1 dollar
Slime Block     1                    8 Dollars             5 dollars
Honey Block   1                    45 Dollars           35 dollars
Redstone B     1                    15 Dollars           10 Dollars
Membrane      1                    40 Dollars           25 dollars
Spider Eye       1                   1 Dollar               50 cents
Blaze Rod        1                   35 Dollars           25 dollars
Beacon            1                   25,000 Dollars    5000 dollars
Turtle Egg       1                   50 Dollars           45 dollars
Conduit           1                  100 Dollars          75 dollars
Scute               1                  150 Dollars          100 dollars
Diamond         1                  100 Dollars          50 Dollars Dollars
Diamond B      1                  900 Dollars          450 dollars
String              1                  75 Cents              50 cents
Feather           1                  1.25 Cents            1 dollar
Gunpowder    1                  3 Dollars               2 dollars
Gravel             1                  1.50 Dollars          1 Dollar        
Leather           1                  1.50 Cents            1 dollar
Egg                1                   1 Dollar                50 cents
Ink Sac           1                   8 Dollars              5 dollars
Bone              1                   1 Dollar                50 cents
Ender Pearl    1                   5 Dollars              2 dollars
Nether Wart  1                   3 Dollars              1 dollars
Rabbit Hide   1                  12 Dollars             8 dollars
Chorus Fruit  1                   3 Dollars              2 dollars
Potato           1                   1 Dollar               75 cents
Carrot            1                   1 Dollar              75 cents
Deepslate      1                   2 Dollars            1 dollar 
Tuff                1                   3 Dollars            2 Dollars 
Copper          1                   5 Dollars            3 dollars 
Glow Berries  1                   1.50 Dollars       1 Dollar 
Moss Block    1                   1 Dollar             75 cents 
Candles         1                   2 Dollars            1 dollar 
Amethyst B   1                   30 Dollars          20 dollars 
Calcite          1                   10 Dollars           5 dollars 
Glow Inc Sac 1                  30 Dollars           20 dollars 
Point Drips    1                  2 Dollars             1 Dollar 
Mud              1                  3 Dollars             2 Dollars

**Comment by Whitescan** [comment]
### Feature
All of The price is per 1 block for players to sell to the server.

**Blocks**
- Grass Block 35 cents
- Dirt Block 25 cents
- Cobblestone/stone 25 cents
- Granite 50 cents
- Diorite 50 cents
- Andesite 50 cents
- All overworld Wood Logs 1 dollar
- All nether Wood Logs 4 dollars
- Sand 25 cents
- Sandstone 1 dollar
- Bricks 2 dollars
- Obsidian 1.50 dollars
- Netherrack 25 cents
- Soul Sand and Soul Soil- 1 dollar
- Ice 1 dollar
- Basalt 2 dollars
- End Stone 1 dollar
- All Terracotta 2 dollars
- Melon Block 50 cents
- Hay Bale 12 dollars
- All Prismarine Blocks and Sea Lantern 2 dollars
- All Concrete and Concrete Powder 3 dollars
- Dried Kelp Block 8 dollars
- All Blackstone 5 dollars
- Glowstone block- 3 dollars
- Magma Block- 5 dollars
- Deepslate - 1.25 dollar 
- Tuff- 5 dollar 

**Wool**
- All wools 3 dollars

**Material**
- Gold Ingot 20 dollars
- Iron ingot 1 dollar
- Quartz 35 dollars
- Emerald 2 dollar
- Coal 2 dollars
- Netherite Scrap 50 dollars
- Phantom Membrane 25 dollars
- Spider’s Eye 50 cents
- Blaze Rod 25 dollars
- Scute 75 dollars
- Diamond 25 Dollars
- String 50 cents
- Feather 1 dollar
- Gunpowder 2 dollars
- Flint 1 dollar
- Leather 1 dollar
- Egg 50 cents
- Ink Sac 5 dollars
- Bone 50 cents
- Ender Pearl 2 dollars
- Nether Wart 2 dollars
- Nether Star 4500
- Rabbit Hide 10 dollars
- Copper 3 dollars 

**Food**
- Pumpkin 50 cents
- Chorus Fruit 2 dollars

**Crops**
- Sugar Cane 50 cents
- Bamboo 25 cents
- Cactus 1 dollar
- Potato 75 cents
- Carrot 75 cents

**Redstone**
- Slime Block 5 dollars
- Honey Blocks 35 dollars
- Redstone Dust 1 dollar
- Conduit 75 dollars

**Special**
- All Heads 1 dollar
- Beacon 5000 dollars
- Turtle Egg 45 dollars


Xp orb- 5 cents (make it so people can bottle their xp)


Glow Berries - 1 dollar 
Moss Block - 75 cents 
All candles - 1 dollar 
Block of Amethyst - 20 dollars 
Calcite - 5 dollars 
Glow Inc Sac - 20 dollars

**Admin Shop Pricing  (Dollar) for (amount)**

Mob Shop
Magma cream- 100 dollars for 8

Naut Shell- 50 dollars for 1

Gunpowder- 80 for 8

Ghast Tear- 8 for 180

String- 10 for 40

Bone- 16 for 80

Blaze Rod- 16 for 200

Phantom Membrane- 1 for 50

Leather- 16 for 150

Rabbit Hide- 16 for 200

Ender Pearls- 16 for 120

Glow Ink Sac - 16 for 250 

Slime block- 1 for 100

Rabbit foot- 1 for 25

Rotten Flesh - 1 for 4

Egg- 1 for 3 dollar

Feather- 1 for 2 dollars


Nether Shop
Black Stone- 16 for 200

Warped and Crimson logs- 16 for 100

Twisting and weeping vines- 16 for 50

Soul sand and Soul soil- 16 for 40

Basalt- 16 for 100

Glowstone- 16 for 75




Log Shop
All Logs- 16 for 80


Valuables 
Redstone- 16 for 50

Diamonds- 1 for 80

Iron- 16 for 100

Lapiz- 25 for 50

Coal- 16 for 80



Dye Shop 
All dye- 8 for 64


Agriculture 
Pumpkin- 16 for 50

Melon- 16 for 50

Honey Block- 1 for 200

Wheat Seeds- 32 for 40

Bamboo- 32 for 50

Sugar Cane- 16 for 40

Kelp- 16 for 50

Large Dripleaf - 16 for 16

Lil Dripleaf 16 for 16




Block Shop
Cobblestone- 64 for 100

Stone- 64 for 100

Andesite- 64 for 100

Diorite- 64 for 100

Granite- 64 for 100

Sand- 64 for 125

Gravel- 64 for 125

Sponge- 1 for 25

Bricks- 32 for 150

Obsidian- 1 for 20

Purpur- 32 for 200

Ice- 16 for 50

Prismarine shards and crystals- 32 for 150

Sea Lanterns- 16 for 100

All terracotta- 32 for 150

Snow Block- 8 for 50

Deepslate - 32 for 100

Calcite - 8 for 50

Amethyst - 8 for 175

Tinted Glass - 4 for 30

All Wool- 1 for  dollar



Pet Shop
Golden Horse Armor- 1 for 75

Diamond Horse Armor- 1 for 250

Iron Horse Armor- 1 for 100

Leather Horse Armor- 1 for 50

Sadel- 1 for 200

**Comment by Whitescan** [comment]
# Item                   Quantity      Buy Price        Sell Price

Blocks:
	Cobblestone          1            50 Cents          25 Cents
	Stone                     1            50 Cents          25 Cents
	Granite                  1            50 Cents          25 Cents
	Diorite                   1            50 Cents          25 Cents
	Andesite                1            50 Cents          25 Cents
	Grass Block            1            65 Cents          35 Cents
	Dirt Block               1            50 Cents          25 Cents
	All logs                  1             2 Dollars         1 Dollar 
	Sand                      1             50 Cents          25 Cents
	Sandstone             1             2 Dollars          50 Cents
	All Glass                1             2 Dollars           1 Dollar 
	Quartz Block        1             90 Dollars           45 Dollars
	Bricks           1              5 Dollars             3 Dollars
	Netherrack          1               50 Cents              25 cents
	Soul Sand           1               1.50 Dollar           1 Dollar      
	Soul Soil             1               1.50 Dollar           1 Dollar
	Ice                      1                1.50 Dollars         1 Dollar
	Basalt                 1                3 Dollars              2 dollars
	End Stone          1                2 Dollars              1 dollar
	All Terracotta    1                  3 Dollars               2 dollars
	All Concretes          1                  2.50 Dollars         1 Dollar
	All Concrete Powders       1                  2.50 Dollars         1 Dollar
	Blackstone       1                  4.50 Dollars         2 Dollars
	Glowstone    1                  5 Dollars              3 dollars
	Magma Block  1                   5 Dollars              3.50 dollars
	Gravel             1                  1.50 Dollars          1 Dollar        
	Deepslate      1                   2 Dollars            1 dollar 
	Tuff                1                   3 Dollars            2 Dollars 
	Candles         1                   2 Dollars            1 dollar 
	Amethyst Block   1                   30 Dollars          20 dollars 
	Calcite          1                   10 Dollars           5 dollars 
	Pointed Dripstone    1                  2 Dollars             1 Dollar 
	Mud              1                  3 Dollars             2 Dollars

Crops:
	Pumpkin              1               2 Dollars             1.50 cents
	Melon Block     1                 2 Dollars              1.50 cents
	Hay Bale           1                 7 Dollars              5 Dollars
	Dried Kelp Block    1                  8 Dollars               4 Dollars
	Sugar Cane     1                   1 Dollar                50 cents
	Bamboo          1                   50 Cents              25 cents
	Cactus             1                   1.50 Cents           1 dollar
	Chorus Fruit  1                   3 Dollars              2 dollars
	Potato           1                   1 Dollar               75 cents
	Carrot            1                   1 Dollar              75 cents
	Moss Block    1                   1 Dollar             75 cents 
	Glow Berries  1                   1.50 Dollars       1 Dollar 

Redstone:
	Slime Block     1                    8 Dollars             5 dollars
	Honey Block   1                    45 Dollars           35 dollars
	Redstone B     1                    15 Dollars           10 Dollars
	Conduit           1                  100 Dollars          75 dollars

Material
	All Wool                1             2 Dollars           1.50 Dollar
	Gold Ingot            1             35 Dollars          20 Dollars 
	Iron ingot             1               10 Dollars           5 Dollars
	Quartz                  1               10 Dollars           5 Dollars
	Obsidian              1              3 Dollars             1.50 Dollar
	Emerald             1                20 Dollars             5 Dollars
	Coal                  1                 4 Dollars              2 dollars
	Prismarine Shard     1                 50 Cents              25 Cents
	Prismarine Crystals     1                 50 Cents              25 Cents
	Netherite I       1                 1,740 Dollars         1000 Dollars
	Membrane      1                    40 Dollars           25 dollars
	Spider Eye       1                   1 Dollar               50 cents
	Blaze Rod        1                   35 Dollars           25 dollars
	Scute               1                  150 Dollars          100 dollars
	Diamond         1                  100 Dollars          50 Dollars Dollars
	String              1                  75 Cents              50 cents
	Feather           1                  1.25 Cents            1 dollar
	Gunpowder    1                  3 Dollars               2 dollars
	Leather           1                  1.50 Cents            1 dollar
	Ink Sac           1                   8 Dollars              5 dollars
	Bone              1                   1 Dollar                50 cents
	Ender Pearl    1                   5 Dollars              2 dollars
	Nether Wart  1                   3 Dollars              1 dollars
	Rabbit Hide   1                  12 Dollars             8 dollars
	Copper          1                   5 Dollars            3 dollars 
	Glow Inc Sac 1                  30 Dollars           20 dollars 

Misc:
	Beacon            1                   25,000 Dollars    5000 dollars
	Turtle Egg       1                   50 Dollars           45 dollars
	Egg                1                   1 Dollar                50 cents

**Comment by Whitescan** [comment]
Implemented under balancing concerns...
This economy felt unstable while implementing it.
