### ISSUE TITLE
Economy tweaks 

### ISSUE THREAD

**Issue by West107** [imperialvalordev/helpdesk#33]
### Features

1) Have each Shop NPC in Spawn have the shop gui and on the page that the shop is.
(ex, Valuables npc would automatically be on the valuables shop page) 

2) Change categories
crop icon to carrot 
Materials to Valuables and put Diamond as Icon
replace redstone with mobdrops category (bone as icon)
Nether Shop (netherwart as icon)

3) Move Items
Obsidian in blocks category

Put membrane, spider eyes, rod, scute ,glow ink sac, string, feather, gunpowder, leather, ink sac, pearl, bone, and hide, wool, Both Eggs in mob drops

Put redstone in valuables 
Move Honey + Slime block to Blocks
Move Conduit to Misc

4) Add items
Rotten Flesh in Mob drops   1     50 Cents       25 Cents
Rabbit Foot in Mob Drops   1      5 Dollars      2 Dollars

Add Dye Shop    1      2 Dollars        1 Dollar

Wheat Seeds in Crops    1     50 Cents    25 Cents
Kelp in Crops      1        1 Dollar       50 Cents 
Drip Leaves in crops    1       1 Dollar    50 Cents

Sponges in Misc    1      50 Dollars      10 Dollars     

Saddle in Misc       1      

Weeping/Twisted Vines      1       1 Dollar       50 Cents  
Move Glowstone in here
Move Magma blocks in here

5) Remove
Get rid of glow berries in materials
Beacon purchasing

**Comment by Whitescan** [comment]
1) is not possible as the plugin is incapable of doing so.

**Comment by Whitescan** [comment]
Features have been implemented as descriped.

> 1. is not possible as the plugin is incapable of doing so.
