### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by aarushbhutra** [imperialvalordev/helpdesk#4]
### Feature

- A report plugins which stores reports in MySQL. Format /report <Player> <Reason>. Sent to staff like 
REPORT <TIME OF REPORT>

<TARGET>
<REPORTER>
<REASON>

### Ideal solution or implementation

N/A

### Alternative solutions or implementations

N/A

### Other context

N/A

### The platform for which your plugin is to be built against

Bungee if possible or spigot with MySQL

**Comment by chriscn** [comment]
@Whitescan is it worth bundling this (and the inevitable other requests regarding staff) into a `IVStaff`? Could do this with #3 as well. Thinking they'll both be at Bungeecord level.

**Comment by Whitescan** [comment]
> @Whitescan is it worth bundling this (and the inevitable other requests regarding staff) into a `IVStaff`? Could do this with #3 as well. Thinking they'll both be at Bungeecord level.

Yes I was aiming to combine those two in https://github.com/imperialvalordev/Stafftools

**Comment by aarushbhutra** [comment]
How will a bungee and a spigot plugin work together?

**Comment by Whitescan** [comment]
Implemented.
