### ISSUE TITLE
Double Jump doesn't Double Jump

### ISSUE THREAD

**Issue by aarushbhutra** [imperialvalordev/helpdesk#5]
### Issue description

1. Jump twice

### Please specify which server you were on.

Lobby

### Operating system

Windows??

### Priority this issue should have

Medium (should be fixed soon)

**Comment by Whitescan** [comment]
> ### Issue description
> 
>     1. Jump twice
> 
> 
> ### Please specify which server you were on.
> 
> Lobby
> ### Operating system
> 
> Windows??
> ### Priority this issue should have
> 
> Medium (should be fixed soon)

Stacktraces? Any info on this?

**Comment by chriscn** [comment]
Please find v0.0.1 here: [DoubleJump](https://github.com/imperialvalordev/DoubleJump/releases/latest)

Permission node is `imperialvalor.doublejump.use`

Still need to add the follow
- Cooldown
- ActionBar
- Toggle command #6
