### ISSUE TITLE
Cross Server Chat

### ISSUE THREAD

**Issue by aarushbhutra** [imperialvalordev/helpdesk#9]
### Feature

I was thinking maybe a plugin on bungeecord which allowed cross server chat? so in config.yml you could specify what server players can see chat in.  Eg: <Server><Rank><Name> : <Message> 

### Ideal solution or implementation

N?A

### Alternative solutions or implementations

N?A

### Other context

N?A

### The platform for which your plugin is to be built against

Bungeecord/Waterfall

**Comment by chriscn** [comment]
Please provide an example of a config file that you would like to use.

**Comment by aarushbhutra** [comment]
allowed server:
- "bwlobby"
- "swlobby"
- "prlobby"

format : "%server%%rank%%name% : %message%"
